metadata.format.version = "1.1"

[versions]
minestom = "2026.01.08-1.21.11"
platform = "3.7.1"

[libraries]
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
platform = { module = "me.devnatan:inventory-framework-platform", version.ref = "platform" }