metadata.format.version = "1.1"

[versions]
minestom = "2025.12.20-1.21.11"
platform = "3.5.5"

[libraries]
minestom = { module = "net.minestom:minestom", version.ref = "minestom" }
platform = { module = "me.devnatan:inventory-framework-platform", version.ref = "platform" }