name: Build
run-name: Build and deploy by @${{ github.actor }}

env:
  REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
  REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository == 'CytonicMC/minestom-inventory-framework'
    runs-on: ubuntu-latest
    env:
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: false

      - name: Publish Jar
        run: ./gradlew --no-daemon --build-cache --configuration-cache --parallel publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}