name: Build
run-name: Build and deploy by @${{ github.actor }}

env:
  REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
  REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  publish:
    if: github.repository == 'CytonicMC/minestom-inventory-framework'
    runs-on: ubuntu-latest
    env:
      REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish Jar
        run: gradle --no-daemon publish
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}